### PR TITLE
Issue #75 Di Container Support.

### PR DESCRIPTION
**Pull request by dylanmcguire**
Hey Guys, 

Here's my attempt at adding some support for dependency injection in gauge projects. This is working well for what we need it to do on our projects.

Added support for DI container using Autofac. Can be enabled by setinng use_di to true in the properties file. When enabled extensions of Autofac's Module class present in gauge project assemblies can be used to register types against the container.

### CODE REVIEW

**Comment by sriv** [comment]
Hi @dylanmcguire - Thanks a lot for putting this in place. We are looking at the changeset in order to merge it. It might be take some time, as there are two more pulls waiting to be merged. 

In the meatime, could you please look at the [Gauge CLA](http://getgauge.io/cla/index.html) and sign it? This is required for us to merge this pull request. Thanks!

**Comment by sriv** [comment]
@dylanmcguire - I had a look at the changeset, and here is what I observe:

- I like the [IClassInstanceManager](https://github.com/dylanmcguire/gauge-csharp/blob/822539ee30eb79c9ad549749d2fa410ef548535e/Runner/InstanceManagement/IClassInstanceManager.cs) being extracted out
- The pull request seems to focus on wiring up Autofac as the container
- The Gauge.CSharp.Runner project now has a dependency on Autofac.

I think since we would like this feature to support multiple tools, and the runner itself need not have a static reference, since Gauge.CSharp does not use any DI framework at the moment.

What do you say about having a contract via `IClassInstanceManager` being exposed to the user as part of say `Gauge.CSharp.Lib`, similar to [`IScreenGrabber`](https://github.com/getgauge/gauge-csharp/blob/master/Lib/IScreenGrabber.cs), and the user can configure it to wire up any container that is convenient? 

The runner can look for custom resolver similar to how it [looks for Custom ScreenShot](https://github.com/getgauge/gauge-csharp/blob/master/Runner/AssemblyLoader.cs#L117).

**Comment by dylanmcguire** [comment]
Hey Srikanth,

Yea I agree allowing the Gauge.CSharp.Runner to remain DI container
agnostic sounds like a better option. I'll work on making this change and
issue a new pull request.

Thanks for your feedback, Dylan

**Comment by sriv** [comment]
Hey Dylan - cheers! Look forward to the new pull request! I'll leave this one open for now just for tracking.

**Comment by dylanmcguire** [comment]
Hey Srikanth,

I've made the change but I've got one question before I issue the pull
request. Now the csharp runner needs to take a dependency on a newer
version of the Libs project. How should I go about making this newer
version available? Should I publish it to the nuget gallery (not sure if I
need some kind of permissions) or should I just issue the pull request and
let you guys handle this?

Thanks, Dylan

**Comment by sriv** [comment]
Hey Dylan,

Awesome work!

So, there are couple of things to note here:

- @tomzo sent us a couple of pull requests that add C# support for mono, which means you can run C# with gauge in Linux/OSX !! 
- As part of that, the build scripts needed to be migrated to use Fake instead of plain PS.

So, I would recommend that you rebase with master if you haven't done so already.

Coming to your questions:

Lib is a Nuget package, and nuget requires permissions to publish which only the Gauge team has right now. I think the most practical thing to do would be to send your pull request, and we can take care of publishing it. If you feel you would like to see things through, let me know and I will try to set you up with some way to publish the Lib.

cheers - Srikanth

**Comment by dylanmcguire** [comment]
Alright thanks Srikanth! I've issued the new pull request. Let me know if I
should make any other changes.

Thanks, Dylan

**Comment by henkeja** [comment]
What is the status on this? This is a feature our dev team needs to move forward with our work.

**Comment by sriv** [comment]
@henkeja - there is a release upcoming (pending one fix) that adds support for mono via pr #74. We will merge this request post that, thanks for understanding.

**Comment by sriv** [comment]
Commits now available in master, for some reason merge didn't close the PR. 

@dylanmcguire - thank you for the contribution, much appreciated. FYI - there is now a [myget feed](https://www.myget.org/feed/Packages/gauge-csharp) to host Lib/Core nuget packages for dev purposes. 

@henkeja - we need to do some more stuff around this - mostly around documentation, but also releasing the Gauge CSharp Lib nuget package. The feature should be available in the next release.

**Pull request closed without merging**
